### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by batosai** [cnumr/ecoindex_api#421]
### What happened?

Hello,

after an API call /v1/tasks/ecoindexes, my task goes to FAILURE status. Using Flower I noticed a typing error on the version of chrome. To get past this, I added the ENV var CHROME_VERSION_MAIN to my .env file. This enabled me to move on to the next stage and obtain a SUCCESS. Unfortunately, the result is still inconclusive:

```
'{"status": "FAILURE", "detail": null, "error": {"detail": {"args": [], "exception": "WebDriverException", "message": "unknown error: cannot connect to chrome at 127.0.0.1:59747\nfrom chrome not reachable"}, "exception": "WebDriverException", "message": "unknown error: cannot connect to chrome at 127.0.0.1:59747\nfrom chrome not reachable", "status_code": 500, "url": "https://www.apple.com"}}'
```

Could you help me?

Thank you

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Hello @batosai thank you for your issue.
You are right about the environment version! I have to fix this!

What is the chrome main version you are using ?

I noticed issue since the version +3.1 of the API. I am investigating on the reason, but for now, I advise you to use the [v3.0.0](https://github.com/cnumr/ecoindex_api/releases/tag/v3.0.0)...

**Comment by batosai** [comment]
Hello, it's ok with v3.0.0

thank you and congratulations for this job
